"""
THIS CONTENTS OF THIS FILE SHOULD BE COPIED TO A NEW
FILE CALLED secret.py. THIS NEW FILE SHOULD NOT BE
ADDED TO VERSION CONTROL. THIS DEFAULT FILE SHOULD
BE KEPT AS-IS WITHIN VERSION CONTROL.
"""

PEER_TESTING_API_ACCESS_TOKEN = ''

SOCIAL_AUTH_GITLAB_KEY = ''
SOCIAL_AUTH_GITLAB_SECRET = ''
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = ''
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = ''
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY = ''
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET = ''
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_TENANT_ID = ''
# Social Django configuration for Microsoft Azure Active Directory
# https://python-social-auth.readthedocs.io/en/latest/backends/azuread.html
