# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.SlugField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('i', 'Invisible to Students'), ('c', 'Closed for Submissions'), ('u', 'Self-Testing and Solutions'), ('f', 'Peer-Testing and Feedback')], default='i', max_length=1)),
                ('runtime', models.CharField(choices=[('', 'No Execution'), ('p3', 'Python 3'), ('j8', 'Java 8')], default='', max_length=8)),
                ('test_class', models.CharField(max_length=128)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.SlugField(max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('s', 'Solution to Coursework'), ('c', 'Test Case for Solution'), ('r', 'Results of Running Test Case'), ('d', 'Coursework Task Descriptor, sample files'), ('e', 'Executable that tests run against that gives expected output'), ('i', 'Test solution matches signature, interface, compiles, etc.')], max_length=1)),
                ('display_name', models.CharField(max_length=64, null=True)),
                ('latest_version', models.IntegerField(default=0)),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Coursework')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestMatch',
            fields=[
                ('id', models.SlugField(max_length=8, primary_key=True, serialize=False)),
                ('test_version', models.IntegerField()),
                ('solution_version', models.IntegerField()),
                ('error_level', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('s', 'Solution to Coursework'), ('c', 'Test Case for Solution'), ('r', 'Results of Running Test Case'), ('d', 'Coursework Task Descriptor, sample files'), ('e', 'Executable that tests run against that gives expected output'), ('i', 'Test solution matches signature, interface, compiles, etc.')], max_length=1)),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_cw', to='common.Coursework')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tm_res_sub', to='common.Submission')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_sol_sub', to='common.Submission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_test_sub', to='common.Submission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrolleduser',
            unique_together=set([('login', 'course')]),
        ),
    ]
